config/routes.rb
Sensors::Application.routes.draw do
  resources :readings

end

app/models/reading.rb
class Reading < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @readings, callback: params[:jsoncallback] }
    end
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
    @reading = Reading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/new
  # GET /readings/new.json
  def new
    @reading = Reading.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/1/edit
  def edit
    @reading = Reading.find(params[:id])
  end

  # POST /readings
  # POST /readings.json
  def create
    @reading = Reading.new(params[:reading])

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
        format.json { render json: @reading, status: :created, location: @reading }
      else
        format.html { render action: "new" }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /readings/1
  # PUT /readings/1.json
  def update
    @reading = Reading.find(params[:id])

    respond_to do |format|
      if @reading.update_attributes(params[:reading])
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading = Reading.find(params[:id])
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to readings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sensors</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/readings/_form.html.erb
<%= form_for(@reading) do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :temperature %><br />
    <%= f.number_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :humidity %><br />
    <%= f.number_field :humidity %>
  </div>
  <div class="field">
    <%= f.label :light %><br />
    <%= f.number_field :light %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.erb
<h1>Listing readings</h1>

<table>
  <tr>
	<th>Time</th>
    <th>Temperature</th>
    <th>Humidity</th>
    <th>Light</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @readings.each do |reading| %>
  <tr>
    <td><%= reading.created_at %></td>
    <td><%= reading.temperature %></td>
    <td><%= reading.humidity %></td>
    <td><%= reading.light %></td>
    <td><%= link_to 'Edit', edit_reading_path(reading) %></td>
    <td><%= link_to 'Show', reading %></td>
    <td><%= link_to 'Destroy', reading, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reading', new_reading_path %>

app/views/readings/new.html.erb
<h1>New reading</h1>

<%= render 'form' %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Temperature:</b>
  <%= @reading.temperature %>
</p>

<p>
  <b>Humidity:</b>
  <%= @reading.humidity %>
</p>

<p>
  <b>Light:</b>
  <%= @reading.light %>
</p>


<%= link_to 'Edit', edit_reading_path(@reading) %> |
<%= link_to 'Back', readings_path %>